import StatsGridWithImage2 from '@/components/services'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Alain Terrieur | Nos services</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <StatsGridWithImage2></StatsGridWithImage2>
      </main>
    </>
  )
}